---
title: "Result visualization"
#output: html_notebook
---
This notebook is used for visualizing the results from V-phaser2 and the Shannon entropies that are generated by using the project pipeline in script project_script.Rmd. 

# Loading data
```{r}
path_to_shannon_files = "~student12/project/results/shannon_entropy/"

library(tidyverse)

# List the data
file_list = list.files(path_to_shannon_files, pattern = "shannon_" ,full.names = TRUE)

column_names = c()
shannon_entropies = data.frame()

# Load the data in the folder
for (file in file_list){
  
  column_names = cbind(column_names, tools::file_path_sans_ext(basename(file)))
  shannon_entropies = rbind(shannon_entropies, t(read.table(file)))
  
}

# Needing to transpose data and rename columns
shannon_entropies = as.data.frame(t(as.matrix(shannon_entropies)))
colnames(shannon_entropies) = column_names

```

# Shannon Entropy
## Mean Shannon Entropy with standard error of the mean
```{r}
# Calculate standard error of the mean
standard_error = function(x) sd(x) / sqrt(length(x))

# Calculate mean entropy and standard error of the mean
mean_entropies = sapply(shannon_entropies, mean)
se = sapply(shannon_entropies, standard_error)
x = 0:5
```

```{r}
# plot the means and se
par(mfrow = c(1,2), fig=c(0.1,0.7,0.3,0.9)) 
plot(x, mean_entropies[1:6],
    ylim=range(c(mean_entropies[1:6]-se[1:6], mean_entropies[1:6]+se[1:6])),
    pch=19, xlab="Passage", ylab="Mean Shannon entropy +/- SD",
    main="Mean entropy in WT ZIKV passage 0-5")
arrows(x, mean_entropies[1:6]-se[1:6], x, mean_entropies[1:6]+se[1:6], length=0.05, angle=90, code=3)
plot(x, mean_entropies[7:12],
    ylim=range(c(mean_entropies[7:12]-se[7:12], mean_entropies[7:12]+se[7:12])),
    pch=19, xlab="Passage", ylab="Mean Shannon entropy +/- SD",
    main="Mean entropy in WT ZIKV passage 0-5")
arrows(x, mean_entropies[7:12]-se[7:12], x, mean_entropies[7:12]+se[7:12], length=0.05, angle=90, code=3)

```


## Mean Shannon Entropy and coverage

```{r}

path_to_SNP_files = "~student12/project/results/SNP/"

# List the data
cov_file_list = list.files(path_to_SNP_files, pattern = "covplot.R" ,full.names = TRUE)

column_names = c()
coverage = data.frame()

# Load the data in the folder
for (file in cov_file_list){
  
  column_names = cbind(column_names, tools::file_path_sans_ext(basename(file)))
  # Read the file
  source(file)
  # variable y is the vector containing the coverage in the file
  coverage = rbind(coverage, y)
  
}

# Needing to transpose data and rename columns
coverage = as.data.frame(t(as.matrix(coverage)))
colnames(coverage) = column_names

```


```{r}
# Find mean coverage and se
mean_coverage = sapply(coverage, mean)
se_cov = sapply(coverage, standard_error)
```

```{r}
# Combine the mean coverage and mean entropies for convenience
cov_shannon = as.data.frame(cbind(mean_coverage, mean_entropies))

# Replace the rownames with only the strain and passage
row_names = str_replace(rownames(cov_shannon), "SNP_","") %>% str_replace(".covplot","")
rownames(cov_shannon) = row_names
```

```{r}


```


# SNV
## Common SNVs across all passages


```{bash}
  grep -v "#" SNP_WT_P1.fdr.var.txt | cut -f 1,6  > modified_SNP_WT_P1.fdr.var.txt
  grep -v "#" SNP_WT_P2.fdr.var.txt |cut -f 1,6> modified_SNP_WT_P2.fdr.var.txt
  grep -v "#" SNP_WT_P3.fdr.var.txt |cut -f 1,6> modified_SNP_WT_P3.fdr.var.txt
  grep -v "#" SNP_WT_P4.fdr.var.txt |cut -f 1,6> modified_SNP_WT_P4.fdr.var.txt
  grep -v "#" SNP_WT_P5.fdr.var.txt |cut -f 1,6> modified_SNP_WT_P5.fdr.var.txt
```
```{r}
library(tidyverse)

##First we need to obtain under the format of data.frame all the SNVs for each passage.

#set the path of the files :
path_to_SNP_files ="/home/student12/project/results/SNP"
#identifying all the files needed :
all_files = list.files(path_to_SNP_files, pattern ="modified_", full.names = TRUE)
# read in all the CSV files :
all_data_frames <- lapply(all_files, function(x){
  read.csv(x,header = FALSE, sep="\t") } )
#We modify the name of the columns to identify position and frequency, then we create a new collumn containing the number of the passage for each SNV. This will help us later to plot every SNVs by group.
for (i in 1:5) {
  colnames(all_data_frames[[i]]) <- c("Position","Frequency")
  all_data_frames[[i]] <- mutate(all_data_frames[[i]], Passage = i )
}
#We can now reduce our 5 data frames in one.
single_data_frame <- Reduce(rbind, all_data_frames)

#We now can identify and plot on the map of the genome the mutations that appears in one or multiple passages at a frequency of 5% or more in the viral population. We then remove the duplicates or more : 

mutation_of_interest <- filter(single_data_frame, Frequency >= 5) %>%
mutation_of_interest <- arrange(mutation_of_interest, desc(Position)) 
mutation_of_interest <- distinct(mutation_of_interest, Position, .keep_all = TRUE)

ggplot(single_data_frame, aes(x = Passage, y= Frequency)) + labs
#identify the common mutations in the genome
#common_mutation = map(all_data_frames, ~.$Position ) %>%
#  reduce(intersect)

#for (i in 1:5){
#  all_data_frames[[i]] %>%
#    filter(Frequency >= 5.0)%>%
#    arrange(desc(Position))
#}
#plot the map of the genome :
#plot the SNPs per passage and the frequencies : 
```








